version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  flask:
    image: app
    env_file:
      - ./.env
    expose:
      - 8000

volumes:
  db:
